### ISSUE TITLE
Change usage store

### ISSUE THREAD

**Issue by miroslaw-bogacz** [briisk/angular-starter#1]
**Use reducer:**
When your module doesn't have dependencies with other module use `SotreModule.forFeature('counter', reducer);` in the counter module on ngrx-store 4 you don't need to add reducer to the main module.

**Use interface**
Use interface for feature when you injected store provider, you don't need to use AppState interface
```
interface ProductsListState {
  pending: boolean;
  ...
}

interface ProductsState {
  list: ProductsListState
}

constructor(private store: Store<ProductsState>) {}
```

now you can use

```
this.store.select('products', 'list');
```

**Comment by dakolech** [comment]
But we are injecting a store, which has entire state available, right? 
```
// store
const appState = {
  products: {...},
  users: {...},
}

this.store.select('products', 'list');
this.store.select('users', 'list');
```
In the above example, we can select both users and products store in the same example. And we need to always specifiy the entire path, so IMO there should be AppState.

**Comment by miroslaw-bogacz** [comment]
@dakolech  you are right but I don't have problem with that because my application has services for any feature to get data from store

```
@Injectable()
export class IssuesListService {

  private get _issuesListState$(): Observable<IIssuesListState> {
    return this._issuesStore.select('issues', 'issuesList');
  }

  constructor(
    private _issuesStore: Store<IIssuesReducer>,
  ) {}

  public isPending(): Observable<boolean> {
    return this._issuesListState$
      .map((state: IIssuesListState) => state.pending);
  }

  public getIssues(): Observable<Array<any>> {
    return this._issuesListState$
      .filter(Boolean)
      .map((state: IIssuesListState) => state.model.issues);
  }

}
```

and when I need data from two other places I inject two times store to service and then tests is better readable :)

**Comment by dakolech** [comment]
@miroslaw-bogacz it's pretty similar to https://github.com/reactjs/reselect :)

**Comment by dakolech** [comment]
@miroslaw-bogacz btw.,
```
constructor(private store: Store<ProductsState>) {}
```
is not working when you are using function in select:
```
store.select(state => state.products.list);
```
will raise `Unresolved variable products` :)
